### ISSUE TITLE
xmonadで実行時にエラー

### ISSUE THREAD

**Issue by ghsable** [HKey/gwip#1]
シングルモニタでウィンドウマネージャー`xmonad`を使用しています。
ウィンドウをFloat型にして`gwip move --grid=2x3 --place=0,1`を実行すると以下のエラーが発生します。
```
thread 'main' panicked at 'called Result::unwrap() on an Err value: ParseIntError { kind: Empty }', src/libcore/result.rs:999:5
 note: run with RUST_BACKTRACE=1 environment variable to display a backtrace.
```

**Comment by HKey** [comment]
手元で試してみたところでは、内部で呼び出している `xdotool getactivewindow` が失敗しますね。

```
$ xdotool getactivewindow
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
```

この問題はEwmhDesktopsを使うことで回避できるようです。
手元では動作するようになりました。

もしEwmhDesktopsを有効にしていないのであれば、一度確認してもらえますか？

http://hackage.haskell.org/package/xmonad-contrib-0.16/docs/XMonad-Hooks-EwmhDesktops.html

**Comment by ghsable** [comment]
`EwmhDesktops`を無効にした状態で`xdotool getactivewindow`を実行しました。
文言は若干違いますが、こちらの環境でもエラーが再現されました。
```
$ xdotool getactivewindow
Your windowmanager claims not to support _NET_ACTIVE_WINDOW, so the attempt to query the active window aborted.
xdo_get_active_window reported an error
```
提示の方法通り、`EwmhDesktops`を使用することで`xdotool getactivewindow`が通るようになりました。
`~/.xmonad/xmonad.hs`に追加した個所を`+`で示します。
```
-- ~/.xmonad/xmonad.hs
+import XMonad.Hooks.EwmhDesktops
 ...
 main = do
+  xmonad $ ewmh myDefaultConfig
   { ...
   , ...
+  , handleEventHook = ewmhDesktopsEventHook
   }
   ...
```
再び`gwip move --grid=2x3 --place=0,1`を実行したところ、期待する動作が得られました。

こちらはウィンドウマネージャー側の問題と認識しますが、
このような問題に対してFAQ形式等でドキュメント化される予定はありますか？

**Comment by HKey** [comment]
EwmhDesktopsでの動作確認ありがとうございます。
EwmhDesktopsを使うことで問題を回避できる、ということで良さそうですね。

> こちらはウィンドウマネージャー側の問題と認識しますが、
> このような問題に対してFAQ形式等でドキュメント化される予定はありますか？

xmonadでの使用は余り想定していないのですが、回避方法も分かりましたし記載します。
ただ、xmonadの設定方法はgwipの範疇を超えますので、簡単な説明とリンクだけとしたいですね。
自分はxmonadをメインで使っているわけではないので、詳細な設定方法をgwipのドキュメントとして維持することは避けたいためです。

**Comment by HKey** [comment]
簡単ですが `README.md` にFAQとして記載しました。
FAQとKnown Issuesで悩みましたが、xmonad側の問題との認識ですのでFAQとしました。
（「よくある質問」なのかもちょっと悩みましたが、気にしないことにしました ;p）

何かあれば気兼ねなくreopenして下さい。

**Comment by ghsable** [comment]
> 簡単ですが README.md にFAQとして記載しました。

ありがとうございました :D
